# Generated by Django 3.2.7 on 2021-09-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0002_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('comments', models.TextField(max_length=500)),
                ('cmnt_at', models.DateTimeField(auto_now_add=True)),
                ('cmnt_by', models.CharField(max_length=20)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_site.blogmodel')),
            ],
        ),
    ]
