# Generated by Django 3.2.7 on 2021-09-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
