# Generated by Django 3.2.7 on 2021-09-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blog_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
