# Generated by Django 3.2.7 on 2021-09-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0006_remove_blogmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='upload_to',
        ),
    ]
