# Generated by Django 3.2.7 on 2021-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0007_remove_blogmodel_upload_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='public'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
